# https://taskfile.dev
version: '3'
vars:
  BINFILE: mdtohtml
  IMG: sgaunet/mdtohtml:latest

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  linter:
    desc: "Run linter"
    cmds:
      - golangci-lint run

  build:
    desc: "Build the binary"
    cmds:
      - go mod tidy
      - go mod download
      - CGO_ENABLED=0 go build .

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean
