# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtohtml < Formula
  desc "markdown to html converter (with github css style)"
  homepage "https://github.com/sgaunet/mdtohtml"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.1/mdtohtml_0.6.1_Darwin_x86_64.tar.gz"
      sha256 "0aa9ed3947ddf36fa538697ae9107badfe5aa28710a1bb70fdc384f2f2abc7bb"

      def install
        bin.install "mdtohtml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.1/mdtohtml_0.6.1_Darwin_arm64.tar.gz"
      sha256 "142121fbf0783fc9f5dec1d13cec8fbac6026d9f86b9041e621db1d96a4bd959"

      def install
        bin.install "mdtohtml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.1/mdtohtml_0.6.1_Linux_armv6.tar.gz"
      sha256 "819f2670335fe3c8122f6c167d63f9303b1a32f1de8c5d303dc3fa92c833bc40"

      def install
        bin.install "mdtohtml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.1/mdtohtml_0.6.1_Linux_arm64.tar.gz"
      sha256 "a19d6051e15748e81e2a5a7618a9d457e705f4f712966d2910c71208eb7574e8"

      def install
        bin.install "mdtohtml"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sgaunet/mdtohtml/releases/download/v0.6.1/mdtohtml_0.6.1_Linux_x86_64.tar.gz"
      sha256 "8da26a3a5c87d4deda768e4cde9e3458fc6f3ebdba69e8230991bc4a6451bc08"

      def install
        bin.install "mdtohtml"
      end
    end
  end
end
